[package]
name = "app-rusty-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
bytemuck = {version="1.13", features = ["derive"]}
glam = "0.27"
winit = "0.30"
env_logger = "0.11"
log = "0.4"
wgpu = "22.1"
pollster = "0.3"
